http:
  port: "8081"

db:
  host: "ep-misty-dew-ag1jregh-pooler.c-2.eu-central-1.aws.neon.tech" # REPLACE with your actual Neon Host
  port: "5432"
  user: "neondb_owner"
  database: "neondb"

crm:
  host: "reqres.in"
  port: "443"
  basePath: "/api"

inventory:
  # Using app.home ensures it works on CloudHub and Local
  mock_path: "${app.home}/examples/inventory-response.xml"

dlq:
  queue: "dlq"
  
finance:
  frequency: "10"